### ISSUE TITLE
인증 메일 기능 추가

### ISSUE THREAD

**Issue by ysheo** [ysheo/TaskTribe#4]
1. 인증 메일 전송 기능 추가
    - 인증 방법 2가지 고려
    - 1안은 코드 전송 후 입력
    - 2안은 인증 링크 발송
    
2. 회원가입 시 비밀번호 암호화 추가

**Comment by jungsungh** [comment]
2안이 좋을꺼같습니다.

**Comment by sub-bong** [comment]
저도 2안이 좋을 것 같습니다.

**Comment by ysheo** [comment]
오 2안이 많네요~ 2안으로 진행하겟습니다
